name: Metrics

on:
  schedule: [{cron: "15 0 * * *"}]
  push: {branches: ["main"]}
  workflow_dispatch:
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - uses: lowlighter/metrics@latest
        with:
          # Github Settings
          token: ${{ GITHUB_TOKEN }}
          committer_message: "Update Metrics (${{ steps.date.outputs.date }})"
          
          # Options
          base: header, repositories, metadata
          config_timezone: America/New_York
          
          # Most used languages.
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage             
          plugin_languages_threshold: 0%     
        # plugin_languages_colors: "0:orange, javascript:#ff0000"  
        # plugin_languages_ignored: html, css                            
        # plugin_repositories_ignored: my_random_repo
          
          # Lines of code changed
          plugin_lines: yes
