name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "15 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Options
          base: header, repositories, metadata
          config_timezone: America/New_York
          
          # Most used languages.
          plugin_languages: yes
        # plugin_languages_ignored: html, css                          
        # plugin_languages_colors: "0:orange, javascript:#ff0000"    
        # plugin_repositories_ignored: my_random_repo
          plugin_languages_details: bytes-size, percentage             
          plugin_languages_threshold: 0%                               
          plugin_languages_limit: 8  
          
          # Lines of code changed
          plugin_lines: yes
